# Generated by Django 2.2.19 on 2022-10-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221010_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='producer',
        ),
    ]
